styled-components/polished

- package.json
Previously, running `npm run test` would run the tests under both `src/`
**and** `lib/` – the second of which is totally unnecessary.
This disables running tests under the `lib/` folder, but also fixes the
build process to not even move them over to the `lib/` folder.
> Only test src folder

- .documentation.json
- docs/docs/index.html
- src/index.js
- src/shorthands/backgroundImages.js
- src/shorthands/backgrounds.js
- src/shorthands/test/__snapshots__/backgroundImages.test.js.snap
- src/shorthands/test/__snapshots__/backgrounds.test.js.snap
- src/shorthands/test/backgroundImages.test.js
- src/shorthands/test/backgrounds.test.js
Shorthands for multiple backgrounds and background-images
Addresses 2 items in #1
> chore(shorthands): Background & Background Image

- .documentation.json
- docs/docs/index.html
- src/index.js
- src/mixins/normalize.js
- src/mixins/test/__snapshots__/normalize.test.js.snap
- src/mixins/test/normalize.test.js
Normalize mixin that can optionally exclude opionionated rules.
> chore(normalize): Normalize mixin

- .documentation.json
- docs/docs/index.html
- src/helpers/modularScale.js
- src/helpers/rgb.js
- src/helpers/rgba.js
- src/mixins/fontFace.js
- src/mixins/radialGradient.js
- src/mixins/timingFunctions.js
- src/shorthands/animation.js
- src/shorthands/buttons.js
- src/shorthands/textInputs.js
For some reason, adding a doc block to the type solves this. I did change some names for consistency and to avoid location hash conflicts (the `TimingFunctions` type and `timingFunctions` method had the same id, so I changed type to `TimingFunction`).
Also, `documentation` still does not recognize some complex types like `Ratio` but it links to the actual code, so it's ok.
Closes #71
> Add missing flow type references

- docs/assets/polished.js
- docs/docs/index.html
- src/mixins/fontFace.js
- src/mixins/normalize.js
https://github.com/styled-components/styled-components/blob/master/docs/api.md#injectglobal
The method name should be injectGlobal instead of injectGlobals or am I missing something?
> Fixed typo in documentation

- src/mixins/placeholder.js
According to the [conversation](https://github.com/styled-components/polished/pull/41#discussion_r91830362), I think the `mixins` do not work with `css` of SC.
> docs(placeholder): reflect the usage

- src/color/parseToRgb.js
- src/color/test/__snapshots__/parseToRgb.test.js.snap
- src/color/test/parseToRgb.test.js
As per the spec: https://drafts.csswg.org/css-color-3/#rgb-color.
> White space characters are allowed around the numerical values.
> chore(color): Allow whitespace in rgb and hsl values.

- docs/assets/polished.js
- docs/docs/index.html
- src/color/opacify.js
- src/color/test/__snapshots__/transparentize.test.js.snap
- src/color/transparentize.js
- yarn.lock
`transparentize(0.9, '#002f6b')` results in `rgba(0,47,107,0.09999999999999998)` and it should be `rgba(0,47,107,0.1)`
> fix(color): Prevent floating point issue with alpha channel

- src/helpers/directionalProperty.js
- src/helpers/test/__snapshots__/directionalProperty.test.js.snap
- src/helpers/test/directionalProperty.test.js
- src/mixins/ellipsis.js
- src/mixins/test/__snapshots__/ellipsis.test.js.snap
- src/mixins/test/ellipsis.test.js
- src/shorthands/borderRadius.js
- src/shorthands/borderWidth.js
- src/shorthands/margin.js
- src/shorthands/padding.js
- src/shorthands/position.js
- src/shorthands/size.js
- src/shorthands/test/__snapshots__/borderRadius.test.js.snap
- src/shorthands/test/__snapshots__/borderWidth.test.js.snap
- src/shorthands/test/__snapshots__/margin.test.js.snap
- src/shorthands/test/__snapshots__/padding.test.js.snap
- src/shorthands/test/__snapshots__/position.test.js.snap
- src/shorthands/test/__snapshots__/size.test.js.snap
- src/shorthands/test/borderRadius.test.js
- src/shorthands/test/borderWidth.test.js
- src/shorthands/test/margin.test.js
- src/shorthands/test/padding.test.js
- src/shorthands/test/position.test.js
- src/shorthands/test/size.test.js
This change allows `0` as a valid value for the `directionalProperty` helper. Previously a zero value would be ignored and left unset.
In practical terms, it means you can type `position(0)` whereas before you had to type `position('0')`.
> Permit number inputs including allowing zero as a valid value.

- .documentation.json
- docs/assets/polished.js
- docs/docs/index.html
- src/color/readableColor.js
- src/color/test/__snapshots__/readableColor.test.js.snap
- src/color/test/readableColor.test.js
Uses W3C convention to determine if black or white is more readable (greater luminosity difference)
from a given color
The git hooks returned the following error (so I used --no-verify)
```
/polished/docs-theme/index.js:34
let prefix = ''
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```
As part of the precommit build, docs/assets/polished.js and docs/docs/index.html were modified.  I hope that's expected behavior.
Thanks for all of your time and hard work!
> [V2][WIP] feat(Color): Returns most readable color, black or white

- package.json
Later versions of documentation.js introduced a breaking change that is affecting our theme. Until
this can be addressed, pinning this at beta 18.
> build(documentation.js): Pin documentation.js due to a build issue.

- .babelrc
- docs/docs/index.html
- package.json
- rollup.config.js
- yarn.lock
Replace deprecated latest preset with babel-preset-env. Credit to @luftywiranda13. 
#195
> build(babel): Replace deprecated latest preset

- docs/assets/polished.js
- docs/docs/index.html
- src/color/adjustHue.js
- src/color/darken.js
- src/color/desaturate.js
- src/color/lighten.js
- src/color/mix.js
- src/color/opacify.js
- src/color/saturate.js
- src/color/setHue.js
- src/color/setLightness.js
- src/color/setSaturation.js
- src/color/shade.js
- src/color/tint.js
- src/color/transparentize.js
- src/helpers/em.js
- src/helpers/rem.js
- src/mixins/normalize.js
- src/mixins/test/__snapshots__/normalize.test.js.snap
- yarn.lock
Follow-up after https://twitter.com/b_hough/status/878015824056942592
> fix(color): Improve the library size for webpack

- src/color/parseToRgb.js
`parseFloat` does not take a `radix` argument.
> chore(Color): Remove unused argument from 'parseFloat'.

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Adds Code of Conduct and links to it from CONTRIBUTING.MD
> docs(code-of-conduct): Adds Coraline's Code Of Conduct.

- src/mixins/wordWrap.js
"break-all" is not a valid value for overflow-wrap and its alias word-wrap. It's only applicable to the non-standard word-break property. The example in the docs was inconsistent with the logic which accounted for this.
> Use 'break-word' as value in wordWrap example.

- src/index.js
the export of readableColor() is missing in the index.js
`import { readableColor } from 'polished'` does currently not work
> fix(readableColor): add missing export of readableColor to index

- .documentation.json
- docs/assets/polished.js
- docs/docs/index.html
- src/color/getLuminance.js
- src/color/readableColor.js
- src/color/test/__snapshots__/getLuminance.test.js.snap
- src/color/test/getLuminance.test.js
- src/index.js
Closes #148 
At least partially, as it allows the user to get the value, but doesn't have an accompanying setter to change the luminance. It seemed like this was already being handled by other methods.
I feel like to really make this useful, another method would need to allow a user to compare the contrast ratio of two colors and return a boolean stating whether or not it adheres to the [W3C specs](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html#contrast-ratiodef).
> feat(getLuminance): Add getLuminance function

- .travis.yml
Addresses build issue caused by semantic-release moving to support only node 8 (specific to yarn): https://github.com/semantic-release/semantic-release/issues/433
> build(travis): Update travis build to use yarn/node 8 fully.

- src/helpers/directionalProperty.js
- src/helpers/test/__snapshots__/directionalProperty.test.js.snap
- src/helpers/test/directionalProperty.test.js
- src/mixins/ellipsis.js
- src/mixins/test/__snapshots__/ellipsis.test.js.snap
- src/mixins/test/ellipsis.test.js
- src/shorthands/borderRadius.js
- src/shorthands/borderWidth.js
- src/shorthands/margin.js
- src/shorthands/padding.js
- src/shorthands/position.js
- src/shorthands/size.js
- src/shorthands/test/__snapshots__/borderRadius.test.js.snap
- src/shorthands/test/__snapshots__/borderWidth.test.js.snap
- src/shorthands/test/__snapshots__/margin.test.js.snap
- src/shorthands/test/__snapshots__/padding.test.js.snap
- src/shorthands/test/__snapshots__/position.test.js.snap
- src/shorthands/test/__snapshots__/size.test.js.snap
- src/shorthands/test/borderRadius.test.js
- src/shorthands/test/borderWidth.test.js
- src/shorthands/test/margin.test.js
- src/shorthands/test/padding.test.js
- src/shorthands/test/position.test.js
- src/shorthands/test/size.test.js
Shorthand modules have been updated to allow unitless values as integers for better ReactNative
compatibility. Flow types now also reflect this.
Addresses: #246
> feat(shorthands): Shorthands now fully accept integers

- src/helpers/directionalProperty.js
- src/helpers/test/__snapshots__/directionalProperty.test.js.snap
- src/helpers/test/directionalProperty.test.js
- src/shorthands/borderRadius.js
- src/shorthands/test/__snapshots__/borderRadius.test.js.snap
- src/shorthands/test/__snapshots__/borderWidth.test.js.snap
- src/shorthands/test/__snapshots__/margin.test.js.snap
- src/shorthands/test/__snapshots__/padding.test.js.snap
- src/shorthands/test/__snapshots__/position.test.js.snap
- src/shorthands/test/__snapshots__/size.test.js.snap
- src/shorthands/test/borderRadius.test.js
- src/shorthands/test/borderWidth.test.js
- src/shorthands/test/margin.test.js
- src/shorthands/test/padding.test.js
- src/shorthands/test/position.test.js
- src/shorthands/test/size.test.js
https://github.com/styled-components/polished/pull/255 introduced integer values for many shorthand functions. However many of these disallow zero because `0` isn't truthy.
This changes updates `directionalProperty` and `borderRadius` helpers to allow zero, as well as adding several tests.
> Permit zero for directionalProperty, borderRadius

- package.json
- yarn.lock
I've checked and it doesn't introduce any change to your output, but the important issue got fixed in the plugin. Anyway it's always better to upgrade ;)
> chore(deps): Updated babel-plugin-annotate-pure-calls

- docs/assets/style.css
Proposing this color change to improve accessibility, by using a color that has higher contrast ratio against the background. 
Before: 
After:
> docs(style)Improve color contrast for sidebar text

- package.json
- yarn.lock
Lock rollup-plugin-commonjs version to prevent the build from throwing when running `npm install` instead of `yarn install` untill https://github.com/rollup/rollup-plugin-commonjs/issues/275 is resolved.
fixes #279
> build: lock rollup-plugin-commonjs version

- .babelrc
- .babelrc.js
- package.json
- rollup.config.js
- yarn.lock
Fixes #292 
I think `add-module-exports` plugin is not working at the moment, still investigating this.
EDIT:// 🙈 ^ this was a babel plugin ordering issue, i've swapped transform-commonjs and add-module-exports and it works
> fix(build): Centralized babel config to prevent accidental mismatches

- src/index.js
- src/shorthands/border.js
- src/shorthands/test/__snapshots__/border.test.js.snap
- src/shorthands/test/border.test.js
- src/types/sideKeyword.js
Border shorthand for splitting out individual border properties. Especially useful for atmoic css
libraries like Fela and Styletron.
Addresses #264
> feat(border): Border shorthand

- .eslintrc
- src/mixins/ellipsis.js
- src/mixins/test/__snapshots__/ellipsis.test.js.snap
- src/mixins/test/ellipsis.test.js
Add `display: inline-flex` for browsers that support it better handle white-space issues with
`display: inline-block`
Addresses #256
> fix(ellipsis): Harden ellipsis mixin.

- README.md
I just had seen that link goes wrong, while was meeting with the lib, fixed with a cap of tea :)
> Fix link url to contributors' page

- README.md
Hello,
This is a great lib I just discovered. I stumbled upon a minor in the README: the value to most functions such as `darken, desaturate, lighten...` seems to be a percentage (between 0-1) in the docs, but in this README it's a value between 0-100.
> docs(README): color module examples incorrect

- src/color/mix.js
- src/color/test/__snapshots__/mix.test.js.snap
- src/color/test/mix.test.js
Introducing a breaking change with mix that now requires the weight in order to function. The
previous version that tried to make the first param optional with a fallback broke with Babel
compilation and currying, and also did not provide the original intended API.
BREAKING CHANGE: Mix no longer has a default weight, it must always be provided.
> fix(mix): Fix first param issues with mix.

- src/color/parseToRgb.js
- src/color/test/__snapshots__/parseToHsl.test.js.snap
- src/color/test/parseToHsl.test.js
Regexes updated to allow parseToHSL(a) to handle float values for hue.
fixes #343
> fix(parseToHSL): parseToHSL(A) can now handle float values for hue

- docs/assets/polished.js
- docs/docs/index.html
- src/color/parseToHsl.js
- src/color/parseToRgb.js
- Adds usage of `parseToRgb` and `parseToHsl` in their code samples
- Corrects `parseToHsl` code samples to show the actual expected output
> docs: Improved docs for parseToRgb and parseToHsl

- docs/assets/polished.js
- package.json
- src/color/shade.js
- src/color/test/__snapshots__/shade.test.js.snap
- src/color/test/__snapshots__/tint.test.js.snap
- src/color/tint.js
We were accidentally mixing white WITH our color.
See these examples:
- [How tint works within sass (expected behavior)](https://www.sassmeister.com/gist/437db2a2cbb0d59fa6808b1e03151549)
- [How tint works within polished (unexpected behavior)](https://codesandbox.io/s/9q297pyn8o)
Current behavior:
```js
const tinted = tint(0.4, "#454859"); // #b4b5bc - unexpected
const mixed1 = mix(0.4, "#454859", "#ffffff"); // #b4b5bc - expected
const mixed2 = mix(0.4, "#ffffff", "#454859"); // #8f919b - expected AND how tint should work
```
New/fixed behavior:
```js
const tinted = tint(0.4, "#454859"); // #8f919b - expected
const mixed1 = mix(0.4, "#454859", "#ffffff"); // #b4b5bc - expected
const mixed2 = mix(0.4, "#ffffff", "#454859"); // #8f919b - expected
```
> feat(color): Update tint and shade to mix a color WITH white

- src/color/setSaturation.js
It says 'The lightness range...' where it should say 'The saturation range...'. 😊
> docs: fix typo in setSaturation function

- docs/assets/polished.js
- docs/docs/index.html
- package.json
- src/math/math.js
- src/math/test/math.test.js
Fixes two bugs with `math`. 
- Time units (and angles) are now supported. 
- Also properly works in IE11 (doesn't support Object.values). Thanks @goldsziggy
fix #405 & #407
> fix(math): Time units and IE11

- README.md
- package.json
- adds `sideEffects: false` to the package.json
- reorganizes package.json
- moves babel-plugin-preval to `devDependencies`
- Updates `README.MD` with note about `moduleResolution: node`
> [v3.0.3] - Build Updates and README.MD

- src/color/parseToRgb.js
If you'd like to proceed with this then let me know and I'll add tests.
**Reasoning**
Browsers accept uppercase (or mixed) in rgb/hsl strings so I think it would be good to support this here too.
> Use case insensitive regexes in parseToRgb

- src/color/adjustHue.js
- src/internalHelpers/_hslToRgb.js
- src/internalHelpers/test/__snapshots__/_hslToRgb.test.js.snap
- src/internalHelpers/test/_hslToRgb.test.js
> Fix(adjustHue): account for potential negative hue value

- src/color/parseToRgb.js
- src/color/test/__snapshots__/parseToRgb.test.js.snap
- src/color/test/__snapshots__/transparentize.test.js.snap
- src/color/test/parseToRgb.test.js
- src/color/test/transparentize.test.js
Issue: 
parseToRgb's hslaRegex did not allow for decimals in the Saturation and Lightness values.
```
../node_modules/polished/lib/color/parseToRgb.js:156
throw new _errors["default"](5);
^
Error: Couldn't parse the color string. Please provide the color as a string in hex, rgb, rgba, hsl or hsla notation.
```
Caused by: `"hsla(218, 36.4%, 95.7%, 1.0)"`
Explanation:
In our repo we recently changed to using hsla over hex values.  A designer then realised that the colours we translated to were not exact to those in the design system so we are now using a new conversion site (https://www.ginifab.com/feeds/pms/rgb_to_hsv_hsl.html) and this has given us decimal values in saturation and lightness
More test results from regex101 for HSLA:
I'm guessing this would affect HSL as well, but feedback …
> feat(hsla): enable decimal values in hsla

- src/helpers/getValueAndUnit.js
- src/helpers/stripUnit.js
Mark stripUnit's optional return for deprecation in favor of keeping getValueAndUnit.
> chore(stripunit): mark stripUnit optional return for deprecation

- .documentation.json
- .github/workflows/main.yml
- docs/assets/polished.js
- docs/docs/index.html
- package.json
- src/color/mix.js
- src/color/readableColor.js
- src/color/test/__snapshots__/mix.test.js.snap
- src/color/test/__snapshots__/readableColor.test.js.snap
- src/color/test/__snapshots__/shade.test.js.snap
- src/color/test/__snapshots__/tint.test.js.snap
- src/color/test/mix.test.js
- src/color/test/readableColor.test.js
- src/helpers/cssVar.js
- src/helpers/getValueAndUnit.js
- src/helpers/stripUnit.js
- src/helpers/test/cssVar.test.js
- src/index.js
- src/internalHelpers/errors.md
- yarn.lock
We're super stoked to announce that polished.js v3.5.0 is officially out! It is available via your package manager of choice. This will be the final non-patch release before v4.
`npm install polished`
`yarn add polished`
* **`cssVar`**: We've introduced a new module to handle fetching CSS Variable values. We chose to make this a standalone module as opposed to integrating it into all modules to keep module size down.
* **`readableColor`**: You can now turn on strict mode for custom provided return colors. This will ensure that they still meet AA contrasting standards. Otherwise, they will return `black` or `white` as normal. This mode is off by default in v3.5. (Thanks @mrmckeb).
* **`mix`, `tint`, `shade`**: Fixed a bug where `mix` was improperly weighting alpha channels to the second …
> Version 3.5.0 Release

- package.json
- src/helpers/getValueAndUnit.js
- src/helpers/modularScale.js
- src/helpers/stripUnit.js
- src/helpers/test/__snapshots__/stripUnit.test.js.snap
- src/helpers/test/stripUnit.test.js
- src/mixins/between.js
- src/mixins/triangle.js
* **`between`, `modularScale`, `triangle`:** fixed issue where these modules were calling deprecated functionality in `stripUnit` and creating unnecessary console noise (and subsequent performance problems).
> Version 3.5.1 Release

- docs/assets/polished.js
- docs/docs/index.html
- package.json
- src/helpers/cssVar.js
`getComputedStyle` is returning values with a leading space when pulled from a CSS file (vs set with JS).`cssVar` now properly trims that space in order to parse values properly.
fix #493
> fix(cssvar): trim space from cssVar fetched value

- package.json
- rollup.config.js
Remove esmodules:true from babel/pre-env config to fix es5 builds in ie11.
fix #504
> fix(package.json): remove esmodules: true from to fix ie11

- src/helpers/cssVar.js
- src/helpers/test/cssVar.test.js
- src/internalHelpers/errors.md
Allow the user to pass a default value to cssVar for when a variable is not found.
> feat(cssvar): allow a default value for cssVar

- package.json
- src/color/rgbToColorString.js
- src/color/test/__snapshots__/rgbToColorString.test.js.snap
- src/color/test/rgbToColorString.test.js
Fixes issue where passing 0 alpha improperly returned a non-transparent hex color.
fix #515
> fix(rgbtostring): fix issue with 0 alpha rgb colors

- package.json
- src/helpers/cssVar.js
cssVar properly errors when no document object is present in non-browser environments.
fix #518
> fix(cssvar): properly error when there is no document

- src/mixins/ellipsis.js
- src/mixins/test/ellipsis.test.js
`ellipsis` in v4 with `lines` parameter is returning invalid styles.
```tsx
const Ellipsis = styled.div`
${ellipsis("250px", 3)}
`;
const App = () => (
<Ellipsis>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque
accumsan nunc lectus, quis maximus mauris pharetra ut. Nullam cursus
ullamcorper sem vitae convallis. Pellentesque tempor sit amet nisl id
dapibus. Curabitur non eleifend velit, ac varius nibh. Etiam leo urna,
ullamcorper sed turpis a, maximus tristique orci. Quisque eleifend augue
molestie luctus accumsan. Suspendisse finibus risus vitae ornare
porttitor. In nisl magna, egestas et blandit ut, imperdiet vel augue.
Etiam vel risus et leo egestas convallis id vitae lorem. Pellentesque
maximus elit velit, finibus viverra diam mollis eu. Duis eu dui eget
dolor …
```
> fix(ellipsis): fix invalid styles in multi-line

- .npmignore
Currently, this module is 9mb on disk. Added a bunch of stuff to .npmignore so that they aren't published.
Can check unpacked size via npm https://www.npmjs.com/package/polished
> fix: Add additional files and folders to npmignore

- README.md
- docs/assets/polished.js
- docs/docs/index.html
We're excited to release v3.7.0, polished's first Long Term Support (LTS) branch. We will continue to back-port critical bug and security fixes to this branch until the release of v5, at which point v4 will become the new LTS branch. This release also officially deprecates polished v2.x.x.
`npm install polished@lts`
`yarn add polished@lts`
* **`between`**: now properly throws an error when mixed units are used for from/toSize and min/maxScreen. This also fixes the same bug in `fluidRange`. (#445)
* **`readableColor`** - Update docs and function signature to be clearer about the use of each parameter.
* - **`transparentize`** - addressed an issue where we weren't handling cases where floats were greater than 2 decimals. (#548)
* **`triangle` Improvement**: once again properly works with …
> Version 3-7-0-release

- src/color/mix.js
These were probably remnants from taking the sass formula, where it describes the weight in a value of 0 to 100, and it was divided by 100.
> remove unnecessary division by 1

- docs/assets/polished.js
- docs/docs/index.html
- src/color/transparentize.js
This is a really tiny fix 🙃 There's an incorrect use of trailing comma and semicolon in example code for `transparentize`, so I fixed it.
I edited only `src/color/transparentize.js`. The other changes under `docs/` are generated automatically.
This is my first contribution to this repository. Feel free to let me know if you have any problem.
> docs(transparentize): fix trailing comma and semicolon in example code

- docs/assets/polished.js
- src/color/parseToRgb.js
- src/color/test/parseToHsl.test.js
- src/color/test/parseToRgb.test.js
- Fix https://github.com/styled-components/polished/issues/610
- Add more test cases for invalid rgba/hsla strings
- Update docs
> fix(parsetorgb): fix rgba/hsla alpha precision

- LICENSE.md
Updated the outdated copyright year to the present.  So there will not be a need for any further license year updates
> Update outdated LICENSE year

- docs/assets/polished.js
- docs/docs/index.html
- src/easings/easeIn.js
- src/easings/easeInOut.js
- src/easings/easeOut.js
- src/mixins/timingFunctions.js
Some minor documentation updates to:
- List all available easing functions explicitly in the docs
- Change sample link to a popular reference site for how the Penner easing functions look
I also thought it would be nice if the TypeScript [type for `functionName`](https://github.com/styled-components/polished/blob/main/src/easings/easeIn.js#L35) was narrowed from just a generic `string` to string literal type of just the valid names (e.g. `'back' | 'circ' | ...`), but figured it might be a breaking change and I can see some updates are in the works. Happy to open a PR for that change though if it's useful and not on the roadmap?
> docs(easing): adding a list of valid function names to easing functions documentation
