styled-components/polished

- .eslintrc
- .gitignore
- .npmignore
- package.json
- linting
- ignore and rc files
> First repo setup

- .travis.yml
- package.json
- src/index.js
- src/mixins/clearfix.js
- src/mixins/test/clearfix.test.js
> Add testing setup

- README.md
- package.json
Closes #10 
I also published v0.0.0 of `polished` to avoid people stealing the name!
> Rename project to polished

- .travis.yml
- package.json
Setup codecov.io for quickly seeing coverage changes in PRs and being able to have a badge in the README. (not yet added)
> chore(coverage): setup codecov

- .editorconfig
- .eslintrc
Just some repo cleanup, added Jest env to `.eslintrc` and added `.editorconfig` so all editors format the code correctly.
> Repo cleanup

- CNAME
Add a CNAME that points to polished.js.org :tada:
> Setup polished.js.org domain

- README.md
Need to create a proper README too of course, but this is a first start to make sure when it's posted on Twitter etc. the card shows the right logo!
> Add the logo to the readme

- docs/index.html
- src/index.js
- src/mixins/size.js
- src/mixins/test/__snapshots__/size.test.js.snap
- src/mixins/test/size.test.js
Add size mixin, docs, and associated tests.
> Add size mixin

- docs/index.html
- rollup.config.js
- src/helpers/stripUnit.js
- src/index.js
- src/mixins/clearFix.js
- src/mixins/ellipsis.js
- src/mixins/hiDPI.js
- src/mixins/hideText.js
- src/mixins/selection.js
- src/mixins/test/__snapshots__/selection.test.js.snap
- src/mixins/test/selection.test.js
- src/mixins/timingFunctions.js
- src/mixins/wordWrap.js
Adds selection mixin.
Also addresses issues in #33 and #40.
> Adds selection mixin

- .eslintrc
Needs to be merged to master, and then all PRs updated!
> chore(linting): disable valid-jsdoc rule

- .documentation.json
- docs/docs/index.html
- src/index.js
- src/mixins/fontFace.js
- src/mixins/test/__snapshots__/fontFace.test.js.snap
- src/mixins/test/fontFace.test.js
@font-face mixin, accepts both file-based and local references. Also is configurable for file formats, font options, and unicode-range.
Addresses an item in #1
> chore(font-face): @font-face mixin

- .documentation.json
- docs/docs/index.html
- src/index.js
- src/mixins/radialGradient.js
- src/mixins/test/__snapshots__/radialGradient.test.js.snap
- src/mixins/test/radialGradient.test.js
Mixin for creating a radial gradient and setting a background fallback.
Addresses item in #1
> Radial Gradient Mixin

- .travis.yml
I switched to Yarn and did some cleanup which resulted in a way faster build time (2min): https://travis-ci.org/styled-components/polished/builds/192093050
> chore(tests): switch to yarn on travis

- src/helpers/rgba.js
- src/helpers/test/__snapshots__/rgba.test.js.snap
- src/helpers/test/rgba.test.js
ups, made a mistake with alpha …
> chore(rgba): fix rgba behaviour

- .documentation.json
- .gitignore
- docs/docs/index.html
- src/index.js
- src/shorthands/borderRadius.js
- src/shorthands/test/__snapshots__/borderRadius.test.js.snap
- src/shorthands/test/borderRadius.test.js
- yarn-error.log
Provides shorthand for applying a radius value to both corners of a side.
> chore(borderRadius): borderRadius shorthand

- .documentation.json
- README.md
- docs/docs/index.html
- src/helpers/adjustHue.js
- src/helpers/complement.js
- src/helpers/grayscale.js
- src/helpers/invert.js
- src/helpers/test/__snapshots__/adjustHue.test.js.snap
- src/helpers/test/__snapshots__/complement.test.js.snap
- src/helpers/test/__snapshots__/grayscale.test.js.snap
- src/helpers/test/__snapshots__/invert.test.js.snap
- src/helpers/test/adjustHue.test.js
- src/helpers/test/complement.test.js
- src/helpers/test/grayscale.test.js
- src/helpers/test/invert.test.js
- src/index.js
Should only be merged after PR https://github.com/styled-components/polished/pull/85 is merged.
> Color functions

- src/mixins/ellipsis.js
- src/mixins/hideText.js
- src/mixins/wordWrap.js
fixed some typos + syntax issues in src files
> fixed some typos + syntax issues

- src/color/adjustHue.js
- src/color/invert.js
Hi all,
Thanks for an amazing library!
I've been using it for a couple of days and noticed a few errors in the docs:
docs(adjustHue): add degree argument
docs(invert): doesn't take an amount argument
> docs(color): Updates examples

- .npmignore
> fix(npm): dont publish .babelrc

- package.json
> Use the correct mains

- src/helpers/modularScale.js
- src/helpers/test/__snapshots__/modularScale.test.js.snap
- src/helpers/test/modularScale.test.js
Fix issue #147 and also allow steps to be set to zero
> fix(helpers): Fix modularScale computation, allow steps to be zero

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- ROADMAP.md
- Add ROADMAP.md with current and future features.
- Update CONTRIBUTING.md with more information.
- Add issues template to better organize submitted issues.
> docs(repo): Add additional info for contributors.

- docs/assets/polished.js
- docs/docs/index.html
- src/mixins/clearFix.js
- src/mixins/test/__snapshots__/clearFix.test.js.snap
- src/mixins/timingFunctions.js
Fixes an issue with clearFix where `content` was blank due to the empty quotes being parsed as a null value.
Addresses: #140
> fix(clearFix): Fixes an issue with content being blank.

- .documentation.json
- README.md
- ROADMAP.md
- docs-theme/assets/style.css
- docs-theme/index._
- docs/assets/polished.js
- docs/assets/style.css
- docs/docs/index.html
- docs/index.html
Updates docs to include usage example and direct link to contributors. Adds notes on usage and tree-shaking, link directly to docs to README. Updates ROADMAP.
#164
> docs(general): Doc improvements and updated roadmap

- .documentation.json
- README.md
- docs/assets/polished.js
- docs/docs/index.html
- src/index.js
- src/mixins/test/__snapshots__/triangle.test.js.snap
- src/mixins/test/triangle.test.js
- src/mixins/triangle.js
Finishes the triangle mixin with an updated API to be more in line with Bourbon's implementation.
Also updates the associated docs and properly exports the module.
#160
> fix(triangle): Complete triangle mixin

- CODEOWNERS
Properly set code owners so we can make requesting reviews easier.
> chore(repo): Set code owners.

- README.md
Add section to docs on how to handle flow errors using .flowignore
#201
> docs(flow): Add .flowignore suggestion to docs

- .documentation.json
- README.md
- docs/assets/polished.js
- docs/docs/index.html
- src/color/readableColor.js
- src/color/test/__snapshots__/readableColor.test.js.snap
- src/color/test/readableColor.test.js
Uses W3C convention to determine if black or white is more readable (greater luminosity difference).
All credit to @LawJolla. This is based on #192 to merge into master.
@nikgraf @mxstbr Decided to not hold off on this until V2. Should mirror the above (already approved) PR.
> feat(Color): Returns most readable color, black or white

- README.md
Update flow docs in README to indicate that we now suppot flow with zero configuration.
> docs(Flow): Update flow docs in README

- package.json
> fix(package.json): Move typescript deps to devDeps

- .babelrc
- rollup.config.js
See https://github.com/styled-components/polished/issues/262#issuecomment-339904411
> perf(tooling): Use loose mode for the babel transpilation

- .documentation.json
- docs/assets/polished.js
- docs/assets/style.css
- docs/docs/index.html
- src/index.js
- src/mixins/hideVisually.js
- src/mixins/test/__snapshots__/hideVisually.test.js.snap
- src/mixins/test/hideVisually.test.js
- typescript-test.ts
Add mixin to visually hide content but leave it accessible to screen readers. (originally #268)
>  feat(mixins): Add hideVisually mixin

- src/shorthands/test/__snapshots__/transitions.test.js.snap
- src/shorthands/test/transitions.test.js
- src/shorthands/transitions.js
Transitions can now apply the same values to multiple properties.
Addresses #232
> feat(transitions): Same transition to multiple properties

- README.md
- package.json
Includes changes requested in #301
> Opencollective opencollective

- src/index.js
- src/mixins/cover.js
- src/mixins/test/__snapshots__/cover.test.js.snap
- src/mixins/test/cover.test.js
- yarn.lock
Adds mixin that provides css for fully covering an area, including an optional offset that acts as a
padding.
Addresses #258
> feat(cover): Adds mixin for cover.

- .documentation.json
- docs-theme/assets/style.css
- docs/assets/polished.js
- docs/assets/style.css
- docs/docs/index.html
Mention the babel plugin in the docs whereas it didn't exist before.
> docs(babel): add plugin

- .documentation.json
- docs-theme/assets/style.css
- docs/assets/polished.js
- docs/assets/style.css
- docs/docs/index.html
Reverts styled-components/polished#308
> Revert "docs(babel): add plugin"

- src/mixins/normalize.js
- src/mixins/test/__snapshots__/normalize.test.js.snap
Upgrade to normalize.css 8.0 and fix bug with abbr[title] fallback.
re #315
> chore(normalize): Upgrade to normalize 8.0

- package.json
- src/mixins/ellipsis.js
- src/shorthands/test/transitions.test.js
- src/shorthands/transitions.js
- typescript-test.ts
- yarn.lock
Re-enabled tsgen to generate TypeScript bindings.
fixes #276
> chore(TypeScript): Re-enable tsgen

- docs/assets/polished.js
- docs/docs/index.html
- package.json
- src/mixins/normalize.js
- src/mixins/test/__snapshots__/normalize.test.js.snap
- src/types/style.js
Adjusted normalize implementation to allow for typings to match styled-components' typings.
Fix #348
> fix(types): Updated types to be compatible with styled-components.

- package.json
https://github.com/styled-components/styled-components/issues/1825
> Remove jsnext:main field

- docs/assets/polished.js
- docs/docs/index.html
- src/mixins/ellipsis.js
- src/mixins/test/__snapshots__/ellipsis.test.js.snap
Remove inline-flex from ellipsis mixin as it was breaking in more cases than it was actually solving
an edge case with inline-block.
Fix #360
> fix(ellipsis): Remove inline-flex from ellipsis.

- docs/assets/polished.js
- src/mixins/fontFace.js
- src/mixins/normalize.js
Fixes #364 
Not sure if I need to add the import of createGlobalStyle, and the naming of the const's.
> Fix docs regarding deprecated injectGlobal

- docs/assets/polished.js
- src/mixins/test/__snapshots__/triangle.test.js.snap
- src/mixins/test/triangle.test.js
- src/mixins/triangle.js
- yarn.lock
I forgot to test float values last time, just added a test for it now. Sorry about that! 😅
> add ability to use float values for triangle width/height

- src/mixins/between.js
New to polished, reading the docs. Pretty sure this is a syntax error as is.
> Fix syntax error

- docs-theme/docs/index._
- docs/docs/index.html
> docs(layout): hide docs summary on small viewport as well

- package.json
- src/mixins/linearGradient.js
- src/mixins/radialGradient.js
- yarn.lock
1. upgrade flow-bin to `v0.92.1`
2. fix `undefined in tagged template literal` type error:
> fix(flow): undefined in tagged template literal with flow-bin 0.92.1

- docs/assets/polished.js
- docs/docs/index.html
- package.json
- src/math/math.js
- src/math/test/math.test.js
Replaced negative lookbehind for matching seconds.
> fix(math): Fix negative lookbehind

- package.json
- src/internalHelpers/_errors.js
- src/internalHelpers/test/_errors.test.js
Error link in production was pointing to a non-existant folder.
fix #418
> fix(errors): Fix error link

- src/color/readableColor.js
- src/color/test/__snapshots__/readableColor.test.js.snap
- src/color/test/readableColor.test.js
> feat(readableColor): add strict mode option to meet WCAG AA

- package.json
- yarn.lock
Removes accidental extraneous js:next bundle reference.
fix #502
> fix(package.json): remove extraneous js:next bundle

- src/mixins/test/__snapshots__/triangle.test.js.snap
- src/mixins/triangle.js
triangle now returns properties in a way that allows inherit to work by declaring an individual side
for the triangle color.
> fix(triangle): triangle now properly supports inherit

- src/easings/easeIn.js
- src/easings/easeInOut.js
- src/easings/easeOut.js
- src/easings/test/__snapshots__/easeIn.test.js.snap
- src/easings/test/__snapshots__/easeInOut.test.js.snap
- src/easings/test/__snapshots__/easeOut.test.js.snap
- src/easings/test/easeIn.test.js
- src/easings/test/easeInOut.test.js
- src/easings/test/easeOut.test.js
> feat(easings): separate timingFunctions into separate easing functions

- package.json
- src/mixins/linearGradient.js
Fixes issue with rgba values having spaces and being used at the first color stop value.
fix #538
> fix(lineargradient): fix issue with rgba value as the first color stop

- docs/assets/polished.js
- docs/docs/index.html
- package.json
- src/color/readableColor.js
- src/color/test/readableColor.test.js
- yarn.lock
* `readableColor` - Update docs and function signature to be clearer about the use of each parameter.
> Version 4.0.5 Release

- docs/assets/polished.js
- package.json
- src/color/parseToRgb.js
- src/color/test/parseToHsl.test.js
- src/color/test/parseToRgb.test.js
- **Color Modules** - addresses an issue with longer floats in color values. (#610)
> Version 4.2.2
